### PR TITLE
Fancy rating rendering

### LINKED ISSUE #515: Completed matches with unfinalised rating render weirdly
image

### PR DESCRIPTION
**Pull request by j-mao**
Closes #515

### CODE REVIEW

**Comment by n8kim1** [comment]
@gaurav-arya  you generally have a better eye for UI/UX than I do, could you take this one?

**Comment by gaurav-arya** [comment]
Hmm I kind of liked seeing old and new ratings rather than only diff?

**Comment by j-mao** [comment]
Hmm, I suppose part of the point of this PR is to show the magnitude of the rating change (which is harder to immediately see from just old and new, but very easy from the diff). Any suggestions on how to do this while also keeping old/new as you prefer?

**Review by gaurav-arya — APPROVED** [review]
Okay, makes sense:)

**Pull request merged**
