### PR TITLE
Factories Loaders and Token Validity

### PR DESCRIPTION
**Pull request by lowtorola**
This PR does the following:
- [x] Refactors all API hook keys and functions to "factories," which make these able to be used in various places.
  - [x] compete factories
  - [x] user factories
  - [x] team factories
  - [x] episode factories
- [x] Adds React Router Loader Functions for each page in our frontend! 🎉 
  - [x] Submissions
  - [x] MyTeam
  - [x] Scrimmaging
  - [x] Rankings
  - [x] Queue
  - [x] Tournaments
  - [x] Tournament
  - [x] Home
- [x] Checks for token presence/validity before checking for the current episode's info or current team/user info

Need to test:
- [x] Test behavior of invalid token
- [x] Try making a queryFn called in a loader throw an Error/ResponseError, verify that it toasts as desired

### CODE REVIEW

**Comment by lowtorola** [comment]
Not to toot my own horn but that commit is pretty epic some real late night success 😎

**Comment by acrantel** [comment]
Great job! I skimmed the code and it looks good, is there anything specific in this PR you'd want me to take a look at?

**Comment by lowtorola** [comment]
@acrantel I fixed the token validity issue!! Basically just added an `await` in `App.tsx` that blocks app loading until we verify that the token is valid. Lmk if you think this is fine (performance seemed just fine to me). I had to change the `target` in `tsconfig.json` to `es2017` though, is that fine? 😎

**Review by acrantel — APPROVED** [review]
:shipit:

**Pull request merged**
