### PR TITLE
Password Reset

### LINKED ISSUE #793: Implement Password Reset
Currently, "reset password" is not implemented in the frontend2 ui. Need a modal that adds this funcitonality.

### PR DESCRIPTION
**Pull request by lowtorola**
Adds the "request" and "do" reset password pages! Resolves #793 :rocket:

Unfortunately, I am not sure how to test this in staging since the staging api doesn't seem to send password reset links... so maybe we just test this in prod? :shipit:

### CODE REVIEW

**Comment by n8kim1** [comment]
"staging api doesn't seem to send password reset links..." yeah, oops
If you want -- you can edit the backend locally to make it send emails (and auth to our email service). But this might be harder than it's worth

**Comment by lowtorola** [comment]
@n8kim1 Yeahhhh... we'll test it in prod.

:shipit:

**Comment by acrantel** [comment]
image
changed the forgot password page to this

**Comment by acrantel** [comment]
image
image

password reset page

**Pull request merged**
