### PR TITLE
Disallow empty package name on backend

### PR DESCRIPTION
**Pull request by gaurav-arya**
I think this is sufficient, because in some sense the backend behaviour for empty package names isn't "wrong" so long as engine accepts it.

### CODE REVIEW

**Comment by n8kim1** [comment]
could you open an issue to investigate backend behavior etc? but ya good for now

**Review by n8kim1 — DISMISSED** [review]

**Comment by n8kim1** [comment]
"file an issue" well ig this works too lmao

why submissions still "compile" seems oddddd....maybe maybe file an issue for that? could be problem in saturn or
gradle?

**Review by n8kim1 — CHANGES_REQUESTED** [review]
does this need a migration to be generated i think it does

**Comment by gaurav-arya** [comment]
ack that's above my paygrade... Do i just run `makemigrations` and push?

**Comment by n8kim1** [comment]
ya, make sure CI passes too ofc

**Review by n8kim1 — APPROVED** [review]

**Comment by j-mao** [comment]
I'm not convinced this should be enforced at a database level. Future devs may choose to support additional languages where "package" is not a concept that makes sense, in which case it should be left empty. This is a Saturn-side bug.

**Pull request merged**
