### PR TITLE
Improvements to scrimmage requests

### PR DESCRIPTION
**Pull request by gaurav-arya**
See commit list for changes

### CODE REVIEW

**Comment by j-mao** [comment]
Can we use some sort of multi-select field instead of repeated dropdowns?

Something like this could be interesting: https://react-select.com/home

**Review by j-mao — DISMISSED** [review]

**Comment by j-mao** [comment]
Shall we block merge, pending max-number-of-maps-per-scrim constraints?

**Comment by gaurav-arya** [comment]
Sounds good.

**Review by j-mao — APPROVED** [review]
@gaurav-arya could you please review and merge if ok

**Review by n8kim1 — APPROVED** [review]

**Pull request merged**
