### PR TITLE
Allow matches to be deleted

### PR DESCRIPTION
**Pull request by j-mao**

### CODE REVIEW

**Comment by n8kim1** [comment]
for admin panel, if you select a set of last N matches, does it just work? or do you have to select in order?

either way this should be fine yay

**Comment by n8kim1** [comment]
also is it possible for tournamentround deletion to automagically delete its matches too?

**Review by n8kim1 — DISMISSED** [review]
pls see comments but ya

**Comment by j-mao** [comment]
> also is it possible for tournamentround deletion to automagically delete its matches too?

this was #603.

**Review by n8kim1 — APPROVED** [review]

**Pull request merged**
