### PR TITLE
Added loading indication for the password forget interface 

### LINKED ISSUE #22: Add loading indications to password reset interfaces
When buttons are clicked, there is no indication of activity until after things load; this makes some pages seem like they're doing nothing. Users might get frustrated and assume "site's down", or they could spamclick, both are bad

### PR DESCRIPTION
**Pull request by maggiehuiliyao**
closes #22

### CODE REVIEW

**Comment by maggiehuiliyao** [comment]
i'm not sure how you wanted the loading interface to work so if you want me to change it, let me know! this time I managed not to commit over a hundred files yay :>

**Comment by n8kim1** [comment]
Looks good _so far_! Could you add an indicator to the `passwordChange` page as well? Should be nearly identical

**Review by n8kim1 — CHANGES_REQUESTED** [review]
(add for passwordChange.jsx)

**Comment by n8kim1** [comment]
force push to fix merge conflicts that were my cause

**Pull request merged**
